version: 0.0
os: linux
files:
  - source: /dist
    destination: /home/ubuntu/app/src/main/resources/static
hooks:
  ApplicationStop:
    - location: scripts/stop_vue.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/copy_vue_to_static.sh
      timeout: 60
      runas: root
