version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/vue-project
    overwrite: yes
permissions: #CodeDeploy에서 받은 파일의 권한을 설정한다 (ubuntu는 aws ec2 기본사용자)
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: stop_vue.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: copy_vue_to_static.sh
      timeout: 60
      runas: root
