version: 2.1
orbs:
  aws-s3: circleci/aws-s3@4.0.0
  aws-code-deploy: circleci/aws-code-deploy@3.0.0
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  build_and_deploy_vue:
    docker:
      - image: cimg/node:lts # Node 환경 설정
    steps:
      - checkout
      - run:
          name: Build Vue project
          command: |
            cd mood-tracker
            npm install
            npm run build
      - run:
          name: Package Vue project
          command: |
            mkdir -p deploy
            zip -r deploy/vue-project.zip mood-tracker/dist

      - persist_to_workspace:
          root: .
          paths:
            - deploy

  build_and_deploy_spring_boot:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    steps:
      - checkout
      - run:
          name: Build Spring Boot Project
          command: |
            cd mood-tracker-be
            chmod +x ./gradlew
            ./gradlew build
      - run:
          name: Package Spring Boot project
          command: |
            mkdir -p deploy
            zip back.zip -r ./*
            mv back.zip deploy/spring-boot-project.zip

      - persist_to_workspace:
          root: .
          paths:
            - deploy

  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace: # 저장한 폴더 가져오기
          at: .
      - aws-s3/copy:
          from: deploy/* # deploy 폴더 내부의 모든 파일을 aws s3로 보낸다
          to: "s3://ec2-s3-mybucket" # s3 버킷명
          aws-region: AWS_DEFAULT_REGION # CircleCI에 설정한 Context의 내용
      - aws-code-deploy/deploy-bundle:
          application-name: Songtiment
          deployment-group: SongtimentDeployGroup
          deployment-config: CodeDeployDefault.AllAtOnce
          bundle-bucket: ec2-s3-mybucket
          bundle-key: back # 보내는 파일 이름
          bundle-type: zip

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build_and_deploy_vue
      - build_and_deploy_spring_boot
